name: Build Virtual Device App for Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/project-chip/chip-build-android:194
      volumes:
        - "/tmp/log_output:/tmp/test_logs"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Bootstrap
        run: |
          source scripts/bootstrap.sh -p android

      - name: Build virtual-device-app (arm)
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target android-arm-virtual-device-app build"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: virtual-device-app-arm-apk
          path: out/android-arm-virtual-device-app/VirtualDeviceApp/app/outputs/apk/debug/app-debug.apk

      - name: Upload native libs
        uses: actions/upload-artifact@v4
        with:
          name: virtual-device-app-arm-libs
          path: |
            out/android-arm-virtual-device-app/lib/jni/armeabi-v7a/*.so
            out/android-arm-virtual-device-app/lib/*.jar
          if-no-files-found: warn
